
odds_api_key: '262ce187f35c54537c2604af977c1d81'
accu_api_key: '4B8LywkV5ABreulZ2f0DaXqGuuIhfJXI'

run_weeks: [1, 2]
run_years: [2022]

# pred params
pred_params:
  r2_wt: 0
  sera_wt: 0
  mse_wt: 1
  brier_wt: 1
  matt_wt: 1

pred_vers: "sera{sera_wt}_rsq{r2_wt}_mse{mse_wt}_brier{brier_wt}_matt{matt_wt}_bayes"

# ensemble params
ensemble_params:
  stack_model: 'random'
  r2_wt: 0
  sera_wt: 0
  mse_wt: 1
  brier_wt: 1
  matt_wt: 0
  class_cut: 80
  alpha: 80
  include_models: 2
  kfolds: 3

reg_ens_vers: "{stack_model}_sera{sera_wt}_rsq{r2_wt}_mse{mse_wt}_include{include_models}_kfold{kfolds}"
quant_ens_vers: "{stack_model}_q{alpha}_include{include_models}_kfold{kfolds}"
class_ens_vers: "{stack_model}_c{class_cut}_matt{matt_wt}_brier{brier_wt}_include{include_models}_kfold{kfolds}"
million_ens_vers: "{stack_model}_matt{matt_wt}_brier{brier_wt}_include{include_models}_kfold{kfolds}"

# std dev params
std_dev_params:
  model_type: 'spline'
  class: 'class{class_cut}'
  quant: 'q{alpha}'
  pred: 'pred'

std_dev_type: "{model_type}_{pred}_{class}_{quant}_matt{matt_wt}_brier{brier_wt}_kfold{kfolds}"

metrics_dict:
  spline_pred_class80_q80_matt1_brier1_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1
   
  spline_pred_class80_matt1_brier1_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 0

  spline_pred_q80_matt1_brier1_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_quantile: 1

  spline_class80_q80_matt1_brier1_kfold3:
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1

  spline_pred_class80_q80_matt0_brier1_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1

  spline_pred_class80_matt0_brier1_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1

  spline_pred_q80_matt0_brier1_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_quantile: 1

  spline_class80_q80_matt0_brier1_kfold3:
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1

  spline_pred_class80_q80_matt1_brier5_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1

  spline_pred_class80_matt1_brier5_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1

  spline_pred_q80_matt1_brier5_kfold3:
    pred_fp_per_game: 1
    pred_fp_per_game_quantile: 1

  spline_class80_q80_matt1_brier5_kfold3:
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1
  
  spline_pred_class80_q80_matt1_brier1_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1
   
  spline_pred_class80_matt1_brier1_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 0

  spline_pred_q80_matt1_brier1_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_quantile: 1

  spline_class80_q80_matt1_brier1_kfold1:
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1

  spline_pred_class80_q80_matt0_brier1_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1

  spline_pred_class80_matt0_brier1_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1

  spline_pred_q80_matt0_brier1_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_quantile: 1

  spline_class80_q80_matt0_brier1_kfold1:
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1

  spline_pred_class80_q80_matt1_brier5_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1

  spline_pred_class80_matt1_brier5_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_class: 1

  spline_pred_q80_matt1_brier5_kfold1:
    pred_fp_per_game: 1
    pred_fp_per_game_quantile: 1

  spline_class80_q80_matt1_brier5_kfold1:
    pred_fp_per_game_class: 1
    pred_fp_per_game_quantile: 1